### PR TITLE
Updates to Continuous Integration Config

### PR DESCRIPTION
**Pull request by GaurangTandon**
Oj version is now 9.x
Remove clang
Update to ubuntu 18.04

### CODE REVIEW

**Review by AnimeshSinha1309 — APPROVED** [review]

**Comment by AnimeshSinha1309** [comment]
Wait, do not merge. Why are you removing compilation via clang?

**Comment by GaurangTandon** [comment]
I do not see any reason to run the same tests for executables from two different compilers. Can you please justify why both gcc executables and clang executables need to be generated?

**Comment by AnimeshSinha1309** [comment]
Just for safety, sometimes there is undefined behavior, lots of it, in C++, and we GCC still manages to make it work, but CLang does not. Having the code tested on both gives us virtual immunity against any issues with the C++ standard, and we have to pay no price for it.

**Comment by GaurangTandon** [comment]
Alright, you may please re-add clang as a compiler and merge this branch. Thanks.

**Pull request merged**
